version: '3.9'
services:
    db:
        image: postgres:13.1-alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: notas
        volumes:
            - ./../db_data:/var/lib/postgresql/data
        restart: always
        ports:
            - '5432:5432'
    server:
        image: app-notas
        depends_on:
            - db
        ports:
            - '4000:4000'
