version: '3.9'
services:
    db:
        image: postgres:13.1-alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: notas
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        container_name: db
    migrate:
        build: ./prisma
        depends_on:
            - db
        env_file:
            - .env
        container_name: app-notas-migrate
    api:
        build: .
        depends_on:
            - db
            - migrate
        ports:
            - '4000:4000'
        env_file:
            - .env
        container_name: app-notas
volumes:
    db_data:
